version: '3.6'
services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    command: "mix run --no-halt"
    environment:
      - VERIFY_TOKEN=INSERT_YOUR_TOKEN_HERE
      - ACCESS_TOKEN=INSERT_YOUR_TOKEN_HERE